services:
  db:
    image: postgres
    restart: unless-stopped

    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: postgres
    
    # volumes:
    #   - /tmp/minibooru-dev-postgres:/var/lib/postgresql/data